spring.application.name=demo

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DemoDB;encrypt=false
spring.datasource.username=super_user
spring.datasource.password=D0ntTryTh1$@Hom3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect